package com.lishibook.mapper;

import com.lishibook.entity.AlbumUser;

public interface AlbumUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table album_user
     *
     * @mbggenerated Wed Jan 22 15:32:02 CST 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table album_user
     *
     * @mbggenerated Wed Jan 22 15:32:02 CST 2014
     */
    int insert(AlbumUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table album_user
     *
     * @mbggenerated Wed Jan 22 15:32:02 CST 2014
     */
    int insertSelective(AlbumUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table album_user
     *
     * @mbggenerated Wed Jan 22 15:32:02 CST 2014
     */
    AlbumUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table album_user
     *
     * @mbggenerated Wed Jan 22 15:32:02 CST 2014
     */
    int updateByPrimaryKeySelective(AlbumUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table album_user
     *
     * @mbggenerated Wed Jan 22 15:32:02 CST 2014
     */
    int updateByPrimaryKey(AlbumUser record);
}