package com.lishibook.mapper;

import com.lishibook.entity.AlbumPicture;

public interface AlbumPictureMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table album_picture
     *
     * @mbggenerated Wed Jan 22 15:32:02 CST 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table album_picture
     *
     * @mbggenerated Wed Jan 22 15:32:02 CST 2014
     */
    int insert(AlbumPicture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table album_picture
     *
     * @mbggenerated Wed Jan 22 15:32:02 CST 2014
     */
    int insertSelective(AlbumPicture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table album_picture
     *
     * @mbggenerated Wed Jan 22 15:32:02 CST 2014
     */
    AlbumPicture selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table album_picture
     *
     * @mbggenerated Wed Jan 22 15:32:02 CST 2014
     */
    int updateByPrimaryKeySelective(AlbumPicture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table album_picture
     *
     * @mbggenerated Wed Jan 22 15:32:02 CST 2014
     */
    int updateByPrimaryKey(AlbumPicture record);
}