package com.lishibook.mapper;

import com.lishibook.entity.ResourceTopic;

public interface ResourceTopicMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_topic
     *
     * @mbggenerated Wed Jan 22 15:32:02 CST 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_topic
     *
     * @mbggenerated Wed Jan 22 15:32:02 CST 2014
     */
    int insert(ResourceTopic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_topic
     *
     * @mbggenerated Wed Jan 22 15:32:02 CST 2014
     */
    int insertSelective(ResourceTopic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_topic
     *
     * @mbggenerated Wed Jan 22 15:32:02 CST 2014
     */
    ResourceTopic selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_topic
     *
     * @mbggenerated Wed Jan 22 15:32:02 CST 2014
     */
    int updateByPrimaryKeySelective(ResourceTopic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_topic
     *
     * @mbggenerated Wed Jan 22 15:32:02 CST 2014
     */
    int updateByPrimaryKey(ResourceTopic record);
}