package com.lishibook.mapper;

import com.lishibook.entity.ResourceFocusgroup;

public interface ResourceFocusgroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_focusgroup
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_focusgroup
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    int insert(ResourceFocusgroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_focusgroup
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    int insertSelective(ResourceFocusgroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_focusgroup
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    ResourceFocusgroup selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_focusgroup
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    int updateByPrimaryKeySelective(ResourceFocusgroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_focusgroup
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    int updateByPrimaryKey(ResourceFocusgroup record);
}