package com.lishibook.mapper;

import com.lishibook.entity.ResourceEdition;

public interface ResourceEditionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_edition
     *
     * @mbggenerated Wed Jan 22 15:32:02 CST 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_edition
     *
     * @mbggenerated Wed Jan 22 15:32:02 CST 2014
     */
    int insert(ResourceEdition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_edition
     *
     * @mbggenerated Wed Jan 22 15:32:02 CST 2014
     */
    int insertSelective(ResourceEdition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_edition
     *
     * @mbggenerated Wed Jan 22 15:32:02 CST 2014
     */
    ResourceEdition selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_edition
     *
     * @mbggenerated Wed Jan 22 15:32:02 CST 2014
     */
    int updateByPrimaryKeySelective(ResourceEdition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_edition
     *
     * @mbggenerated Wed Jan 22 15:32:02 CST 2014
     */
    int updateByPrimaryKey(ResourceEdition record);
}