package com.lishibook.mapper;

import java.util.List;

import com.lishibook.entity.Resource;
import com.lishibook.entity.ResourceFocus;

public interface ResourceFocusMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_focus
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_focus
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    int insert(ResourceFocus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_focus
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    int insertSelective(ResourceFocus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_focus
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    ResourceFocus selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_focus
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    int updateByPrimaryKeySelective(ResourceFocus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_focus
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    int updateByPrimaryKey(ResourceFocus record);
    
    List<Resource> selectFocuses(Integer id);
}