package com.lishibook.mapper;

import com.lishibook.entity.ResourceRelation;

public interface ResourceRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_relation
     *
     * @mbggenerated Wed Jan 22 15:32:02 CST 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_relation
     *
     * @mbggenerated Wed Jan 22 15:32:02 CST 2014
     */
    int insert(ResourceRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_relation
     *
     * @mbggenerated Wed Jan 22 15:32:02 CST 2014
     */
    int insertSelective(ResourceRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_relation
     *
     * @mbggenerated Wed Jan 22 15:32:02 CST 2014
     */
    ResourceRelation selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_relation
     *
     * @mbggenerated Wed Jan 22 15:32:02 CST 2014
     */
    int updateByPrimaryKeySelective(ResourceRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_relation
     *
     * @mbggenerated Wed Jan 22 15:32:02 CST 2014
     */
    int updateByPrimaryKey(ResourceRelation record);
}