package com.lishibook.mapper;

import com.lishibook.entity.UserTopicReply;

public interface UserTopicReplyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_topic_reply
     *
     * @mbggenerated Wed Jan 22 15:32:02 CST 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_topic_reply
     *
     * @mbggenerated Wed Jan 22 15:32:02 CST 2014
     */
    int insert(UserTopicReply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_topic_reply
     *
     * @mbggenerated Wed Jan 22 15:32:02 CST 2014
     */
    int insertSelective(UserTopicReply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_topic_reply
     *
     * @mbggenerated Wed Jan 22 15:32:02 CST 2014
     */
    UserTopicReply selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_topic_reply
     *
     * @mbggenerated Wed Jan 22 15:32:02 CST 2014
     */
    int updateByPrimaryKeySelective(UserTopicReply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_topic_reply
     *
     * @mbggenerated Wed Jan 22 15:32:02 CST 2014
     */
    int updateByPrimaryKeyWithBLOBs(UserTopicReply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_topic_reply
     *
     * @mbggenerated Wed Jan 22 15:32:02 CST 2014
     */
    int updateByPrimaryKey(UserTopicReply record);
}