package com.lishibook.mapper;

import com.lishibook.entity.UserFocusResource;

public interface UserFocusResourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_focus_resource
     *
     * @mbggenerated Wed Jan 22 15:32:02 CST 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_focus_resource
     *
     * @mbggenerated Wed Jan 22 15:32:02 CST 2014
     */
    int insert(UserFocusResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_focus_resource
     *
     * @mbggenerated Wed Jan 22 15:32:02 CST 2014
     */
    int insertSelective(UserFocusResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_focus_resource
     *
     * @mbggenerated Wed Jan 22 15:32:02 CST 2014
     */
    UserFocusResource selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_focus_resource
     *
     * @mbggenerated Wed Jan 22 15:32:02 CST 2014
     */
    int updateByPrimaryKeySelective(UserFocusResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_focus_resource
     *
     * @mbggenerated Wed Jan 22 15:32:02 CST 2014
     */
    int updateByPrimaryKey(UserFocusResource record);
}