package com.lishibook.mapper;

import com.lishibook.entity.UserTopic;

public interface UserTopicMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_topic
     *
     * @mbggenerated Wed Jan 22 15:32:02 CST 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_topic
     *
     * @mbggenerated Wed Jan 22 15:32:02 CST 2014
     */
    int insert(UserTopic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_topic
     *
     * @mbggenerated Wed Jan 22 15:32:02 CST 2014
     */
    int insertSelective(UserTopic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_topic
     *
     * @mbggenerated Wed Jan 22 15:32:02 CST 2014
     */
    UserTopic selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_topic
     *
     * @mbggenerated Wed Jan 22 15:32:02 CST 2014
     */
    int updateByPrimaryKeySelective(UserTopic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_topic
     *
     * @mbggenerated Wed Jan 22 15:32:02 CST 2014
     */
    int updateByPrimaryKey(UserTopic record);
}