package com.lishibook.mapper;

import com.lishibook.entity.UserLink;

public interface UserLinkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_link
     *
     * @mbggenerated Wed Jan 22 15:32:02 CST 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_link
     *
     * @mbggenerated Wed Jan 22 15:32:02 CST 2014
     */
    int insert(UserLink record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_link
     *
     * @mbggenerated Wed Jan 22 15:32:02 CST 2014
     */
    int insertSelective(UserLink record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_link
     *
     * @mbggenerated Wed Jan 22 15:32:02 CST 2014
     */
    UserLink selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_link
     *
     * @mbggenerated Wed Jan 22 15:32:02 CST 2014
     */
    int updateByPrimaryKeySelective(UserLink record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_link
     *
     * @mbggenerated Wed Jan 22 15:32:02 CST 2014
     */
    int updateByPrimaryKey(UserLink record);
}