package com.lishibook.mapper;

import com.lishibook.entity.UserCollections;

public interface UserCollectionsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_collections
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_collections
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    int insert(UserCollections record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_collections
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    int insertSelective(UserCollections record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_collections
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    UserCollections selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_collections
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    int updateByPrimaryKeySelective(UserCollections record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_collections
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    int updateByPrimaryKey(UserCollections record);
}