package com.lishibook.dao;

import com.lishibook.entity.AlbumPicture;

public interface AlbumPictureMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table album_picture
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table album_picture
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    int insert(AlbumPicture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table album_picture
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    int insertSelective(AlbumPicture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table album_picture
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    AlbumPicture selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table album_picture
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    int updateByPrimaryKeySelective(AlbumPicture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table album_picture
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    int updateByPrimaryKey(AlbumPicture record);
}