package com.lishibook.dao;

import com.lishibook.entity.AlbumResource;

public interface AlbumResourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table album_resource
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table album_resource
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    int insert(AlbumResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table album_resource
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    int insertSelective(AlbumResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table album_resource
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    AlbumResource selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table album_resource
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    int updateByPrimaryKeySelective(AlbumResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table album_resource
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    int updateByPrimaryKey(AlbumResource record);
}