package com.lishibook.dao;

import com.lishibook.entity.ResourceTopicReply;

public interface ResourceTopicReplyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_topic_reply
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_topic_reply
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    int insert(ResourceTopicReply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_topic_reply
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    int insertSelective(ResourceTopicReply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_topic_reply
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    ResourceTopicReply selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_topic_reply
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    int updateByPrimaryKeySelective(ResourceTopicReply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_topic_reply
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    int updateByPrimaryKeyWithBLOBs(ResourceTopicReply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_topic_reply
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    int updateByPrimaryKey(ResourceTopicReply record);
}