package com.lishibook.dao;

import com.lishibook.entity.ResourceTopic;

public interface ResourceTopicMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_topic
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_topic
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    int insert(ResourceTopic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_topic
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    int insertSelective(ResourceTopic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_topic
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    ResourceTopic selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_topic
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    int updateByPrimaryKeySelective(ResourceTopic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_topic
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    int updateByPrimaryKey(ResourceTopic record);
}