package com.lishibook.dao;

import com.lishibook.entity.UserFocusResource;

public interface UserFocusResourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_focus_resource
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_focus_resource
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    int insert(UserFocusResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_focus_resource
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    int insertSelective(UserFocusResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_focus_resource
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    UserFocusResource selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_focus_resource
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    int updateByPrimaryKeySelective(UserFocusResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_focus_resource
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    int updateByPrimaryKey(UserFocusResource record);
}