package com.lishibook.dao;

import com.lishibook.entity.UserLinkRequest;

public interface UserLinkRequestMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_link_request
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_link_request
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    int insert(UserLinkRequest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_link_request
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    int insertSelective(UserLinkRequest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_link_request
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    UserLinkRequest selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_link_request
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    int updateByPrimaryKeySelective(UserLinkRequest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_link_request
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    int updateByPrimaryKey(UserLinkRequest record);
}