package com.lishibook.dao;

import com.lishibook.entity.UserTopicReply;

public interface UserTopicReplyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_topic_reply
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_topic_reply
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    int insert(UserTopicReply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_topic_reply
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    int insertSelective(UserTopicReply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_topic_reply
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    UserTopicReply selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_topic_reply
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    int updateByPrimaryKeySelective(UserTopicReply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_topic_reply
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    int updateByPrimaryKeyWithBLOBs(UserTopicReply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_topic_reply
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    int updateByPrimaryKey(UserTopicReply record);
}