package com.lishibook.entity;

import java.util.Date;

public class AlbumResource {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column album_resource.id
	 * @mbggenerated  Wed Jan 22 15:32:02 CST 2014
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column album_resource.resourceid
	 * @mbggenerated  Wed Jan 22 15:32:02 CST 2014
	 */
	private Integer resourceid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column album_resource.name
	 * @mbggenerated  Wed Jan 22 15:32:02 CST 2014
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column album_resource.description
	 * @mbggenerated  Wed Jan 22 15:32:02 CST 2014
	 */
	private String description;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column album_resource.views
	 * @mbggenerated  Wed Jan 22 15:32:02 CST 2014
	 */
	private Integer views;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column album_resource.time
	 * @mbggenerated  Wed Jan 22 15:32:02 CST 2014
	 */
	private Date time;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column album_resource.lastedit
	 * @mbggenerated  Wed Jan 22 15:32:02 CST 2014
	 */
	private Date lastedit;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column album_resource.lastupload
	 * @mbggenerated  Wed Jan 22 15:32:02 CST 2014
	 */
	private Date lastupload;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column album_resource.creatorid
	 * @mbggenerated  Wed Jan 22 15:32:02 CST 2014
	 */
	private Integer creatorid;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column album_resource.id
	 * @return  the value of album_resource.id
	 * @mbggenerated  Wed Jan 22 15:32:02 CST 2014
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column album_resource.id
	 * @param id  the value for album_resource.id
	 * @mbggenerated  Wed Jan 22 15:32:02 CST 2014
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column album_resource.resourceid
	 * @return  the value of album_resource.resourceid
	 * @mbggenerated  Wed Jan 22 15:32:02 CST 2014
	 */
	public Integer getResourceid() {
		return resourceid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column album_resource.resourceid
	 * @param resourceid  the value for album_resource.resourceid
	 * @mbggenerated  Wed Jan 22 15:32:02 CST 2014
	 */
	public void setResourceid(Integer resourceid) {
		this.resourceid = resourceid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column album_resource.name
	 * @return  the value of album_resource.name
	 * @mbggenerated  Wed Jan 22 15:32:02 CST 2014
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column album_resource.name
	 * @param name  the value for album_resource.name
	 * @mbggenerated  Wed Jan 22 15:32:02 CST 2014
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column album_resource.description
	 * @return  the value of album_resource.description
	 * @mbggenerated  Wed Jan 22 15:32:02 CST 2014
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column album_resource.description
	 * @param description  the value for album_resource.description
	 * @mbggenerated  Wed Jan 22 15:32:02 CST 2014
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column album_resource.views
	 * @return  the value of album_resource.views
	 * @mbggenerated  Wed Jan 22 15:32:02 CST 2014
	 */
	public Integer getViews() {
		return views;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column album_resource.views
	 * @param views  the value for album_resource.views
	 * @mbggenerated  Wed Jan 22 15:32:02 CST 2014
	 */
	public void setViews(Integer views) {
		this.views = views;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column album_resource.time
	 * @return  the value of album_resource.time
	 * @mbggenerated  Wed Jan 22 15:32:02 CST 2014
	 */
	public Date getTime() {
		return time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column album_resource.time
	 * @param time  the value for album_resource.time
	 * @mbggenerated  Wed Jan 22 15:32:02 CST 2014
	 */
	public void setTime(Date time) {
		this.time = time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column album_resource.lastedit
	 * @return  the value of album_resource.lastedit
	 * @mbggenerated  Wed Jan 22 15:32:02 CST 2014
	 */
	public Date getLastedit() {
		return lastedit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column album_resource.lastedit
	 * @param lastedit  the value for album_resource.lastedit
	 * @mbggenerated  Wed Jan 22 15:32:02 CST 2014
	 */
	public void setLastedit(Date lastedit) {
		this.lastedit = lastedit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column album_resource.lastupload
	 * @return  the value of album_resource.lastupload
	 * @mbggenerated  Wed Jan 22 15:32:02 CST 2014
	 */
	public Date getLastupload() {
		return lastupload;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column album_resource.lastupload
	 * @param lastupload  the value for album_resource.lastupload
	 * @mbggenerated  Wed Jan 22 15:32:02 CST 2014
	 */
	public void setLastupload(Date lastupload) {
		this.lastupload = lastupload;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column album_resource.creatorid
	 * @return  the value of album_resource.creatorid
	 * @mbggenerated  Wed Jan 22 15:32:02 CST 2014
	 */
	public Integer getCreatorid() {
		return creatorid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column album_resource.creatorid
	 * @param creatorid  the value for album_resource.creatorid
	 * @mbggenerated  Wed Jan 22 15:32:02 CST 2014
	 */
	public void setCreatorid(Integer creatorid) {
		this.creatorid = creatorid;
	}
}