package com.lishibook.entity;

import java.util.Date;

public class AlbumUser {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column album_user.id
	 * @mbggenerated  Wed Jan 22 15:32:02 CST 2014
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column album_user.uid
	 * @mbggenerated  Wed Jan 22 15:32:02 CST 2014
	 */
	private Integer uid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column album_user.name
	 * @mbggenerated  Wed Jan 22 15:32:02 CST 2014
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column album_user.description
	 * @mbggenerated  Wed Jan 22 15:32:02 CST 2014
	 */
	private String description;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column album_user.views
	 * @mbggenerated  Wed Jan 22 15:32:02 CST 2014
	 */
	private Integer views;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column album_user.time
	 * @mbggenerated  Wed Jan 22 15:32:02 CST 2014
	 */
	private Date time;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column album_user.lastedit
	 * @mbggenerated  Wed Jan 22 15:32:02 CST 2014
	 */
	private Date lastedit;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column album_user.lastupload
	 * @mbggenerated  Wed Jan 22 15:32:02 CST 2014
	 */
	private Date lastupload;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column album_user.id
	 * @return  the value of album_user.id
	 * @mbggenerated  Wed Jan 22 15:32:02 CST 2014
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column album_user.id
	 * @param id  the value for album_user.id
	 * @mbggenerated  Wed Jan 22 15:32:02 CST 2014
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column album_user.uid
	 * @return  the value of album_user.uid
	 * @mbggenerated  Wed Jan 22 15:32:02 CST 2014
	 */
	public Integer getUid() {
		return uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column album_user.uid
	 * @param uid  the value for album_user.uid
	 * @mbggenerated  Wed Jan 22 15:32:02 CST 2014
	 */
	public void setUid(Integer uid) {
		this.uid = uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column album_user.name
	 * @return  the value of album_user.name
	 * @mbggenerated  Wed Jan 22 15:32:02 CST 2014
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column album_user.name
	 * @param name  the value for album_user.name
	 * @mbggenerated  Wed Jan 22 15:32:02 CST 2014
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column album_user.description
	 * @return  the value of album_user.description
	 * @mbggenerated  Wed Jan 22 15:32:02 CST 2014
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column album_user.description
	 * @param description  the value for album_user.description
	 * @mbggenerated  Wed Jan 22 15:32:02 CST 2014
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column album_user.views
	 * @return  the value of album_user.views
	 * @mbggenerated  Wed Jan 22 15:32:02 CST 2014
	 */
	public Integer getViews() {
		return views;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column album_user.views
	 * @param views  the value for album_user.views
	 * @mbggenerated  Wed Jan 22 15:32:02 CST 2014
	 */
	public void setViews(Integer views) {
		this.views = views;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column album_user.time
	 * @return  the value of album_user.time
	 * @mbggenerated  Wed Jan 22 15:32:02 CST 2014
	 */
	public Date getTime() {
		return time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column album_user.time
	 * @param time  the value for album_user.time
	 * @mbggenerated  Wed Jan 22 15:32:02 CST 2014
	 */
	public void setTime(Date time) {
		this.time = time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column album_user.lastedit
	 * @return  the value of album_user.lastedit
	 * @mbggenerated  Wed Jan 22 15:32:02 CST 2014
	 */
	public Date getLastedit() {
		return lastedit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column album_user.lastedit
	 * @param lastedit  the value for album_user.lastedit
	 * @mbggenerated  Wed Jan 22 15:32:02 CST 2014
	 */
	public void setLastedit(Date lastedit) {
		this.lastedit = lastedit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column album_user.lastupload
	 * @return  the value of album_user.lastupload
	 * @mbggenerated  Wed Jan 22 15:32:02 CST 2014
	 */
	public Date getLastupload() {
		return lastupload;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column album_user.lastupload
	 * @param lastupload  the value for album_user.lastupload
	 * @mbggenerated  Wed Jan 22 15:32:02 CST 2014
	 */
	public void setLastupload(Date lastupload) {
		this.lastupload = lastupload;
	}
}