package com.lishibook.entity;

import java.util.Date;

public class AlbumPicture {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column album_picture.id
	 * @mbggenerated  Wed Jan 22 15:32:02 CST 2014
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column album_picture.resourcealbumid
	 * @mbggenerated  Wed Jan 22 15:32:02 CST 2014
	 */
	private Integer resourcealbumid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column album_picture.useralbumid
	 * @mbggenerated  Wed Jan 22 15:32:02 CST 2014
	 */
	private Integer useralbumid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column album_picture.visible
	 * @mbggenerated  Wed Jan 22 15:32:02 CST 2014
	 */
	private Integer visible;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column album_picture.time
	 * @mbggenerated  Wed Jan 22 15:32:02 CST 2014
	 */
	private Date time;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column album_picture.filename
	 * @mbggenerated  Wed Jan 22 15:32:02 CST 2014
	 */
	private String filename;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column album_picture.description
	 * @mbggenerated  Wed Jan 22 15:32:02 CST 2014
	 */
	private String description;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column album_picture.filetype
	 * @mbggenerated  Wed Jan 22 15:32:02 CST 2014
	 */
	private String filetype;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column album_picture.filesize
	 * @mbggenerated  Wed Jan 22 15:32:02 CST 2014
	 */
	private Integer filesize;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column album_picture.path
	 * @mbggenerated  Wed Jan 22 15:32:02 CST 2014
	 */
	private String path;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column album_picture.downloads
	 * @mbggenerated  Wed Jan 22 15:32:02 CST 2014
	 */
	private Integer downloads;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column album_picture.uid
	 * @mbggenerated  Wed Jan 22 15:32:02 CST 2014
	 */
	private Integer uid;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column album_picture.id
	 * @return  the value of album_picture.id
	 * @mbggenerated  Wed Jan 22 15:32:02 CST 2014
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column album_picture.id
	 * @param id  the value for album_picture.id
	 * @mbggenerated  Wed Jan 22 15:32:02 CST 2014
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column album_picture.resourcealbumid
	 * @return  the value of album_picture.resourcealbumid
	 * @mbggenerated  Wed Jan 22 15:32:02 CST 2014
	 */
	public Integer getResourcealbumid() {
		return resourcealbumid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column album_picture.resourcealbumid
	 * @param resourcealbumid  the value for album_picture.resourcealbumid
	 * @mbggenerated  Wed Jan 22 15:32:02 CST 2014
	 */
	public void setResourcealbumid(Integer resourcealbumid) {
		this.resourcealbumid = resourcealbumid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column album_picture.useralbumid
	 * @return  the value of album_picture.useralbumid
	 * @mbggenerated  Wed Jan 22 15:32:02 CST 2014
	 */
	public Integer getUseralbumid() {
		return useralbumid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column album_picture.useralbumid
	 * @param useralbumid  the value for album_picture.useralbumid
	 * @mbggenerated  Wed Jan 22 15:32:02 CST 2014
	 */
	public void setUseralbumid(Integer useralbumid) {
		this.useralbumid = useralbumid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column album_picture.visible
	 * @return  the value of album_picture.visible
	 * @mbggenerated  Wed Jan 22 15:32:02 CST 2014
	 */
	public Integer getVisible() {
		return visible;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column album_picture.visible
	 * @param visible  the value for album_picture.visible
	 * @mbggenerated  Wed Jan 22 15:32:02 CST 2014
	 */
	public void setVisible(Integer visible) {
		this.visible = visible;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column album_picture.time
	 * @return  the value of album_picture.time
	 * @mbggenerated  Wed Jan 22 15:32:02 CST 2014
	 */
	public Date getTime() {
		return time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column album_picture.time
	 * @param time  the value for album_picture.time
	 * @mbggenerated  Wed Jan 22 15:32:02 CST 2014
	 */
	public void setTime(Date time) {
		this.time = time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column album_picture.filename
	 * @return  the value of album_picture.filename
	 * @mbggenerated  Wed Jan 22 15:32:02 CST 2014
	 */
	public String getFilename() {
		return filename;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column album_picture.filename
	 * @param filename  the value for album_picture.filename
	 * @mbggenerated  Wed Jan 22 15:32:02 CST 2014
	 */
	public void setFilename(String filename) {
		this.filename = filename;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column album_picture.description
	 * @return  the value of album_picture.description
	 * @mbggenerated  Wed Jan 22 15:32:02 CST 2014
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column album_picture.description
	 * @param description  the value for album_picture.description
	 * @mbggenerated  Wed Jan 22 15:32:02 CST 2014
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column album_picture.filetype
	 * @return  the value of album_picture.filetype
	 * @mbggenerated  Wed Jan 22 15:32:02 CST 2014
	 */
	public String getFiletype() {
		return filetype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column album_picture.filetype
	 * @param filetype  the value for album_picture.filetype
	 * @mbggenerated  Wed Jan 22 15:32:02 CST 2014
	 */
	public void setFiletype(String filetype) {
		this.filetype = filetype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column album_picture.filesize
	 * @return  the value of album_picture.filesize
	 * @mbggenerated  Wed Jan 22 15:32:02 CST 2014
	 */
	public Integer getFilesize() {
		return filesize;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column album_picture.filesize
	 * @param filesize  the value for album_picture.filesize
	 * @mbggenerated  Wed Jan 22 15:32:02 CST 2014
	 */
	public void setFilesize(Integer filesize) {
		this.filesize = filesize;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column album_picture.path
	 * @return  the value of album_picture.path
	 * @mbggenerated  Wed Jan 22 15:32:02 CST 2014
	 */
	public String getPath() {
		return path;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column album_picture.path
	 * @param path  the value for album_picture.path
	 * @mbggenerated  Wed Jan 22 15:32:02 CST 2014
	 */
	public void setPath(String path) {
		this.path = path;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column album_picture.downloads
	 * @return  the value of album_picture.downloads
	 * @mbggenerated  Wed Jan 22 15:32:02 CST 2014
	 */
	public Integer getDownloads() {
		return downloads;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column album_picture.downloads
	 * @param downloads  the value for album_picture.downloads
	 * @mbggenerated  Wed Jan 22 15:32:02 CST 2014
	 */
	public void setDownloads(Integer downloads) {
		this.downloads = downloads;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column album_picture.uid
	 * @return  the value of album_picture.uid
	 * @mbggenerated  Wed Jan 22 15:32:02 CST 2014
	 */
	public Integer getUid() {
		return uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column album_picture.uid
	 * @param uid  the value for album_picture.uid
	 * @mbggenerated  Wed Jan 22 15:32:02 CST 2014
	 */
	public void setUid(Integer uid) {
		this.uid = uid;
	}
}