package com.lishibook.entity;

import java.util.Date;

public class Pictures {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pictures.id
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pictures.rid
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    private Integer rid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pictures.uid
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pictures.filename
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    private String filename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pictures.path
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    private String path;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pictures.time
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    private Date time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pictures.views
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    private Integer views;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pictures.id
     *
     * @return the value of pictures.id
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pictures.id
     *
     * @param id the value for pictures.id
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pictures.rid
     *
     * @return the value of pictures.rid
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    public Integer getRid() {
        return rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pictures.rid
     *
     * @param rid the value for pictures.rid
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    public void setRid(Integer rid) {
        this.rid = rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pictures.uid
     *
     * @return the value of pictures.uid
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pictures.uid
     *
     * @param uid the value for pictures.uid
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pictures.filename
     *
     * @return the value of pictures.filename
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    public String getFilename() {
        return filename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pictures.filename
     *
     * @param filename the value for pictures.filename
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    public void setFilename(String filename) {
        this.filename = filename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pictures.path
     *
     * @return the value of pictures.path
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pictures.path
     *
     * @param path the value for pictures.path
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    public void setPath(String path) {
        this.path = path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pictures.time
     *
     * @return the value of pictures.time
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pictures.time
     *
     * @param time the value for pictures.time
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pictures.views
     *
     * @return the value of pictures.views
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    public Integer getViews() {
        return views;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pictures.views
     *
     * @param views the value for pictures.views
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    public void setViews(Integer views) {
        this.views = views;
    }
}