package com.lishibook.entity;

import java.util.Date;

public class Resource {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column resource.id
	 * @mbggenerated  Wed Jan 22 15:32:02 CST 2014
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column resource.name
	 * @mbggenerated  Wed Jan 22 15:32:02 CST 2014
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column resource.description
	 * @mbggenerated  Wed Jan 22 15:32:02 CST 2014
	 */
	private String description;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column resource.authorid
	 * @mbggenerated  Wed Jan 22 15:32:02 CST 2014
	 */
	private Integer authorid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column resource.time
	 * @mbggenerated  Wed Jan 22 15:32:02 CST 2014
	 */
	private Date time;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column resource.lastedit
	 * @mbggenerated  Wed Jan 22 15:32:02 CST 2014
	 */
	private Date lastedit;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column resource.lasteditorid
	 * @mbggenerated  Wed Jan 22 15:32:02 CST 2014
	 */
	private Integer lasteditorid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column resource.views
	 * @mbggenerated  Wed Jan 22 15:32:02 CST 2014
	 */
	private Integer views;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column resource.editions
	 * @mbggenerated  Wed Jan 22 15:32:02 CST 2014
	 */
	private Integer editions;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column resource.visible
	 * @mbggenerated  Wed Jan 22 15:32:02 CST 2014
	 */
	private Integer visible;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column resource.locked
	 * @mbggenerated  Wed Jan 22 15:32:02 CST 2014
	 */
	private Integer locked;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column resource.content
	 * @mbggenerated  Wed Jan 22 15:32:02 CST 2014
	 */
	private String content;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column resource.id
	 * @return  the value of resource.id
	 * @mbggenerated  Wed Jan 22 15:32:02 CST 2014
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column resource.id
	 * @param id  the value for resource.id
	 * @mbggenerated  Wed Jan 22 15:32:02 CST 2014
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column resource.name
	 * @return  the value of resource.name
	 * @mbggenerated  Wed Jan 22 15:32:02 CST 2014
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column resource.name
	 * @param name  the value for resource.name
	 * @mbggenerated  Wed Jan 22 15:32:02 CST 2014
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column resource.description
	 * @return  the value of resource.description
	 * @mbggenerated  Wed Jan 22 15:32:02 CST 2014
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column resource.description
	 * @param description  the value for resource.description
	 * @mbggenerated  Wed Jan 22 15:32:02 CST 2014
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column resource.authorid
	 * @return  the value of resource.authorid
	 * @mbggenerated  Wed Jan 22 15:32:02 CST 2014
	 */
	public Integer getAuthorid() {
		return authorid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column resource.authorid
	 * @param authorid  the value for resource.authorid
	 * @mbggenerated  Wed Jan 22 15:32:02 CST 2014
	 */
	public void setAuthorid(Integer authorid) {
		this.authorid = authorid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column resource.time
	 * @return  the value of resource.time
	 * @mbggenerated  Wed Jan 22 15:32:02 CST 2014
	 */
	public Date getTime() {
		return time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column resource.time
	 * @param time  the value for resource.time
	 * @mbggenerated  Wed Jan 22 15:32:02 CST 2014
	 */
	public void setTime(Date time) {
		this.time = time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column resource.lastedit
	 * @return  the value of resource.lastedit
	 * @mbggenerated  Wed Jan 22 15:32:02 CST 2014
	 */
	public Date getLastedit() {
		return lastedit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column resource.lastedit
	 * @param lastedit  the value for resource.lastedit
	 * @mbggenerated  Wed Jan 22 15:32:02 CST 2014
	 */
	public void setLastedit(Date lastedit) {
		this.lastedit = lastedit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column resource.lasteditorid
	 * @return  the value of resource.lasteditorid
	 * @mbggenerated  Wed Jan 22 15:32:02 CST 2014
	 */
	public Integer getLasteditorid() {
		return lasteditorid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column resource.lasteditorid
	 * @param lasteditorid  the value for resource.lasteditorid
	 * @mbggenerated  Wed Jan 22 15:32:02 CST 2014
	 */
	public void setLasteditorid(Integer lasteditorid) {
		this.lasteditorid = lasteditorid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column resource.views
	 * @return  the value of resource.views
	 * @mbggenerated  Wed Jan 22 15:32:02 CST 2014
	 */
	public Integer getViews() {
		return views;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column resource.views
	 * @param views  the value for resource.views
	 * @mbggenerated  Wed Jan 22 15:32:02 CST 2014
	 */
	public void setViews(Integer views) {
		this.views = views;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column resource.editions
	 * @return  the value of resource.editions
	 * @mbggenerated  Wed Jan 22 15:32:02 CST 2014
	 */
	public Integer getEditions() {
		return editions;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column resource.editions
	 * @param editions  the value for resource.editions
	 * @mbggenerated  Wed Jan 22 15:32:02 CST 2014
	 */
	public void setEditions(Integer editions) {
		this.editions = editions;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column resource.visible
	 * @return  the value of resource.visible
	 * @mbggenerated  Wed Jan 22 15:32:02 CST 2014
	 */
	public Integer getVisible() {
		return visible;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column resource.visible
	 * @param visible  the value for resource.visible
	 * @mbggenerated  Wed Jan 22 15:32:02 CST 2014
	 */
	public void setVisible(Integer visible) {
		this.visible = visible;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column resource.locked
	 * @return  the value of resource.locked
	 * @mbggenerated  Wed Jan 22 15:32:02 CST 2014
	 */
	public Integer getLocked() {
		return locked;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column resource.locked
	 * @param locked  the value for resource.locked
	 * @mbggenerated  Wed Jan 22 15:32:02 CST 2014
	 */
	public void setLocked(Integer locked) {
		this.locked = locked;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column resource.content
	 * @return  the value of resource.content
	 * @mbggenerated  Wed Jan 22 15:32:02 CST 2014
	 */
	public String getContent() {
		return content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column resource.content
	 * @param content  the value for resource.content
	 * @mbggenerated  Wed Jan 22 15:32:02 CST 2014
	 */
	public void setContent(String content) {
		this.content = content;
	}
}