package com.lishibook.entity;

import java.util.Date;

public class ResourceFocus {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_focus.id
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_focus.fromrid
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    private Integer fromrid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_focus.torid
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    private Integer torid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_focus.groupid
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    private Integer groupid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_focus.desc
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    private String desc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_focus.time
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    private Date time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_focus.id
     *
     * @return the value of resource_focus.id
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_focus.id
     *
     * @param id the value for resource_focus.id
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_focus.fromrid
     *
     * @return the value of resource_focus.fromrid
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    public Integer getFromrid() {
        return fromrid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_focus.fromrid
     *
     * @param fromrid the value for resource_focus.fromrid
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    public void setFromrid(Integer fromrid) {
        this.fromrid = fromrid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_focus.torid
     *
     * @return the value of resource_focus.torid
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    public Integer getTorid() {
        return torid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_focus.torid
     *
     * @param torid the value for resource_focus.torid
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    public void setTorid(Integer torid) {
        this.torid = torid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_focus.groupid
     *
     * @return the value of resource_focus.groupid
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    public Integer getGroupid() {
        return groupid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_focus.groupid
     *
     * @param groupid the value for resource_focus.groupid
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    public void setGroupid(Integer groupid) {
        this.groupid = groupid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_focus.desc
     *
     * @return the value of resource_focus.desc
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    public String getDesc() {
        return desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_focus.desc
     *
     * @param desc the value for resource_focus.desc
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    public void setDesc(String desc) {
        this.desc = desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_focus.time
     *
     * @return the value of resource_focus.time
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_focus.time
     *
     * @param time the value for resource_focus.time
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    public void setTime(Date time) {
        this.time = time;
    }
}