package com.lishibook.entity;

import java.util.Date;

public class ResourceTopic {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_topic.id
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_topic.resourceid
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    private Integer resourceid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_topic.title
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_topic.content
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    private Integer content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_topic.authorid
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    private Integer authorid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_topic.time
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    private Date time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_topic.lastedit
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    private Integer lastedit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_topic.views
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    private Integer views;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_topic.replys
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    private Integer replys;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_topic.visible
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    private Integer visible;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_topic.id
     *
     * @return the value of resource_topic.id
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_topic.id
     *
     * @param id the value for resource_topic.id
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_topic.resourceid
     *
     * @return the value of resource_topic.resourceid
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    public Integer getResourceid() {
        return resourceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_topic.resourceid
     *
     * @param resourceid the value for resource_topic.resourceid
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    public void setResourceid(Integer resourceid) {
        this.resourceid = resourceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_topic.title
     *
     * @return the value of resource_topic.title
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_topic.title
     *
     * @param title the value for resource_topic.title
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_topic.content
     *
     * @return the value of resource_topic.content
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    public Integer getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_topic.content
     *
     * @param content the value for resource_topic.content
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    public void setContent(Integer content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_topic.authorid
     *
     * @return the value of resource_topic.authorid
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    public Integer getAuthorid() {
        return authorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_topic.authorid
     *
     * @param authorid the value for resource_topic.authorid
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    public void setAuthorid(Integer authorid) {
        this.authorid = authorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_topic.time
     *
     * @return the value of resource_topic.time
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_topic.time
     *
     * @param time the value for resource_topic.time
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_topic.lastedit
     *
     * @return the value of resource_topic.lastedit
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    public Integer getLastedit() {
        return lastedit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_topic.lastedit
     *
     * @param lastedit the value for resource_topic.lastedit
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    public void setLastedit(Integer lastedit) {
        this.lastedit = lastedit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_topic.views
     *
     * @return the value of resource_topic.views
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    public Integer getViews() {
        return views;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_topic.views
     *
     * @param views the value for resource_topic.views
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    public void setViews(Integer views) {
        this.views = views;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_topic.replys
     *
     * @return the value of resource_topic.replys
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    public Integer getReplys() {
        return replys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_topic.replys
     *
     * @param replys the value for resource_topic.replys
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    public void setReplys(Integer replys) {
        this.replys = replys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_topic.visible
     *
     * @return the value of resource_topic.visible
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    public Integer getVisible() {
        return visible;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_topic.visible
     *
     * @param visible the value for resource_topic.visible
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    public void setVisible(Integer visible) {
        this.visible = visible;
    }
}