package com.lishibook.entity;

import java.util.Date;

public class ResourceEdition {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column resource_edition.id
	 * @mbggenerated  Wed Jan 22 15:32:02 CST 2014
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column resource_edition.resourceid
	 * @mbggenerated  Wed Jan 22 15:32:02 CST 2014
	 */
	private Integer resourceid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column resource_edition.authorid
	 * @mbggenerated  Wed Jan 22 15:32:02 CST 2014
	 */
	private Integer authorid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column resource_edition.time
	 * @mbggenerated  Wed Jan 22 15:32:02 CST 2014
	 */
	private Date time;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column resource_edition.ip
	 * @mbggenerated  Wed Jan 22 15:32:02 CST 2014
	 */
	private String ip;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column resource_edition.name
	 * @mbggenerated  Wed Jan 22 15:32:02 CST 2014
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column resource_edition.description
	 * @mbggenerated  Wed Jan 22 15:32:02 CST 2014
	 */
	private String description;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column resource_edition.content
	 * @mbggenerated  Wed Jan 22 15:32:02 CST 2014
	 */
	private Integer content;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column resource_edition.reason
	 * @mbggenerated  Wed Jan 22 15:32:02 CST 2014
	 */
	private String reason;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column resource_edition.id
	 * @return  the value of resource_edition.id
	 * @mbggenerated  Wed Jan 22 15:32:02 CST 2014
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column resource_edition.id
	 * @param id  the value for resource_edition.id
	 * @mbggenerated  Wed Jan 22 15:32:02 CST 2014
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column resource_edition.resourceid
	 * @return  the value of resource_edition.resourceid
	 * @mbggenerated  Wed Jan 22 15:32:02 CST 2014
	 */
	public Integer getResourceid() {
		return resourceid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column resource_edition.resourceid
	 * @param resourceid  the value for resource_edition.resourceid
	 * @mbggenerated  Wed Jan 22 15:32:02 CST 2014
	 */
	public void setResourceid(Integer resourceid) {
		this.resourceid = resourceid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column resource_edition.authorid
	 * @return  the value of resource_edition.authorid
	 * @mbggenerated  Wed Jan 22 15:32:02 CST 2014
	 */
	public Integer getAuthorid() {
		return authorid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column resource_edition.authorid
	 * @param authorid  the value for resource_edition.authorid
	 * @mbggenerated  Wed Jan 22 15:32:02 CST 2014
	 */
	public void setAuthorid(Integer authorid) {
		this.authorid = authorid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column resource_edition.time
	 * @return  the value of resource_edition.time
	 * @mbggenerated  Wed Jan 22 15:32:02 CST 2014
	 */
	public Date getTime() {
		return time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column resource_edition.time
	 * @param time  the value for resource_edition.time
	 * @mbggenerated  Wed Jan 22 15:32:02 CST 2014
	 */
	public void setTime(Date time) {
		this.time = time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column resource_edition.ip
	 * @return  the value of resource_edition.ip
	 * @mbggenerated  Wed Jan 22 15:32:02 CST 2014
	 */
	public String getIp() {
		return ip;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column resource_edition.ip
	 * @param ip  the value for resource_edition.ip
	 * @mbggenerated  Wed Jan 22 15:32:02 CST 2014
	 */
	public void setIp(String ip) {
		this.ip = ip;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column resource_edition.name
	 * @return  the value of resource_edition.name
	 * @mbggenerated  Wed Jan 22 15:32:02 CST 2014
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column resource_edition.name
	 * @param name  the value for resource_edition.name
	 * @mbggenerated  Wed Jan 22 15:32:02 CST 2014
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column resource_edition.description
	 * @return  the value of resource_edition.description
	 * @mbggenerated  Wed Jan 22 15:32:02 CST 2014
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column resource_edition.description
	 * @param description  the value for resource_edition.description
	 * @mbggenerated  Wed Jan 22 15:32:02 CST 2014
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column resource_edition.content
	 * @return  the value of resource_edition.content
	 * @mbggenerated  Wed Jan 22 15:32:02 CST 2014
	 */
	public Integer getContent() {
		return content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column resource_edition.content
	 * @param content  the value for resource_edition.content
	 * @mbggenerated  Wed Jan 22 15:32:02 CST 2014
	 */
	public void setContent(Integer content) {
		this.content = content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column resource_edition.reason
	 * @return  the value of resource_edition.reason
	 * @mbggenerated  Wed Jan 22 15:32:02 CST 2014
	 */
	public String getReason() {
		return reason;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column resource_edition.reason
	 * @param reason  the value for resource_edition.reason
	 * @mbggenerated  Wed Jan 22 15:32:02 CST 2014
	 */
	public void setReason(String reason) {
		this.reason = reason;
	}
}