package com.lishibook.entity;

import java.util.Date;

public class ResourceRelation {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column resource_relation.id
	 * @mbggenerated  Wed Jan 22 15:32:02 CST 2014
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column resource_relation.fromrid
	 * @mbggenerated  Wed Jan 22 15:32:02 CST 2014
	 */
	private Integer fromrid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column resource_relation.torid
	 * @mbggenerated  Wed Jan 22 15:32:02 CST 2014
	 */
	private Integer torid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column resource_relation.type
	 * @mbggenerated  Wed Jan 22 15:32:02 CST 2014
	 */
	private String type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column resource_relation.time
	 * @mbggenerated  Wed Jan 22 15:32:02 CST 2014
	 */
	private Date time;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column resource_relation.id
	 * @return  the value of resource_relation.id
	 * @mbggenerated  Wed Jan 22 15:32:02 CST 2014
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column resource_relation.id
	 * @param id  the value for resource_relation.id
	 * @mbggenerated  Wed Jan 22 15:32:02 CST 2014
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column resource_relation.fromrid
	 * @return  the value of resource_relation.fromrid
	 * @mbggenerated  Wed Jan 22 15:32:02 CST 2014
	 */
	public Integer getFromrid() {
		return fromrid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column resource_relation.fromrid
	 * @param fromrid  the value for resource_relation.fromrid
	 * @mbggenerated  Wed Jan 22 15:32:02 CST 2014
	 */
	public void setFromrid(Integer fromrid) {
		this.fromrid = fromrid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column resource_relation.torid
	 * @return  the value of resource_relation.torid
	 * @mbggenerated  Wed Jan 22 15:32:02 CST 2014
	 */
	public Integer getTorid() {
		return torid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column resource_relation.torid
	 * @param torid  the value for resource_relation.torid
	 * @mbggenerated  Wed Jan 22 15:32:02 CST 2014
	 */
	public void setTorid(Integer torid) {
		this.torid = torid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column resource_relation.type
	 * @return  the value of resource_relation.type
	 * @mbggenerated  Wed Jan 22 15:32:02 CST 2014
	 */
	public String getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column resource_relation.type
	 * @param type  the value for resource_relation.type
	 * @mbggenerated  Wed Jan 22 15:32:02 CST 2014
	 */
	public void setType(String type) {
		this.type = type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column resource_relation.time
	 * @return  the value of resource_relation.time
	 * @mbggenerated  Wed Jan 22 15:32:02 CST 2014
	 */
	public Date getTime() {
		return time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column resource_relation.time
	 * @param time  the value for resource_relation.time
	 * @mbggenerated  Wed Jan 22 15:32:02 CST 2014
	 */
	public void setTime(Date time) {
		this.time = time;
	}
}