package com.lishibook.entity;

import java.util.Date;

public class Resource {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.id
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.name
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.description
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     *
     * This field corresponds to the database column resource.creatorid
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    private Integer creatorid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.createtime
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.lasteditid
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    private Integer lasteditid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.lastedittime
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    private Date lastedittime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.views
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    private Integer views;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.content
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.id
     *
     * @return the value of resource.id
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.id
     *
     * @param id the value for resource.id
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.name
     *
     * @return the value of resource.name
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.name
     *
     * @param name the value for resource.name
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.description
     *
     * @return the value of resource.description
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.description
     *
     * @param description the value for resource.description
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.creatorid
     *
     * @return the value of resource.creatorid
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    public Integer getCreatorid() {
        return creatorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.creatorid
     *
     * @param creatorid the value for resource.creatorid
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    public void setCreatorid(Integer creatorid) {
        this.creatorid = creatorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.createtime
     *
     * @return the value of resource.createtime
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.createtime
     *
     * @param createtime the value for resource.createtime
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.lasteditid
     *
     * @return the value of resource.lasteditid
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    public Integer getLasteditid() {
        return lasteditid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.lasteditid
     *
     * @param lasteditid the value for resource.lasteditid
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    public void setLasteditid(Integer lasteditid) {
        this.lasteditid = lasteditid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.lastedittime
     *
     * @return the value of resource.lastedittime
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    public Date getLastedittime() {
        return lastedittime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.lastedittime
     *
     * @param lastedittime the value for resource.lastedittime
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    public void setLastedittime(Date lastedittime) {
        this.lastedittime = lastedittime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.views
     *
     * @return the value of resource.views
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    public Integer getViews() {
        return views;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.views
     *
     * @param views the value for resource.views
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    public void setViews(Integer views) {
        this.views = views;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.content
     *
     * @return the value of resource.content
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.content
     *
     * @param content the value for resource.content
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    public void setContent(String content) {
        this.content = content;
    }
}