package com.lishibook.entity;

import java.util.Date;

public class ResourceTopicReply {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_topic_reply.id
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_topic_reply.topicid
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    private Integer topicid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_topic_reply.authorid
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    private Integer authorid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_topic_reply.time
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    private Date time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_topic_reply.visible
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    private Integer visible;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_topic_reply.content
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_topic_reply.id
     *
     * @return the value of resource_topic_reply.id
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_topic_reply.id
     *
     * @param id the value for resource_topic_reply.id
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_topic_reply.topicid
     *
     * @return the value of resource_topic_reply.topicid
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    public Integer getTopicid() {
        return topicid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_topic_reply.topicid
     *
     * @param topicid the value for resource_topic_reply.topicid
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    public void setTopicid(Integer topicid) {
        this.topicid = topicid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_topic_reply.authorid
     *
     * @return the value of resource_topic_reply.authorid
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    public Integer getAuthorid() {
        return authorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_topic_reply.authorid
     *
     * @param authorid the value for resource_topic_reply.authorid
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    public void setAuthorid(Integer authorid) {
        this.authorid = authorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_topic_reply.time
     *
     * @return the value of resource_topic_reply.time
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_topic_reply.time
     *
     * @param time the value for resource_topic_reply.time
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_topic_reply.visible
     *
     * @return the value of resource_topic_reply.visible
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    public Integer getVisible() {
        return visible;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_topic_reply.visible
     *
     * @param visible the value for resource_topic_reply.visible
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    public void setVisible(Integer visible) {
        this.visible = visible;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_topic_reply.content
     *
     * @return the value of resource_topic_reply.content
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_topic_reply.content
     *
     * @param content the value for resource_topic_reply.content
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    public void setContent(String content) {
        this.content = content;
    }
}