package com.lishibook.entity;

import java.util.Date;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.id
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.email
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.password
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.nickname
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    private String nickname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.gender
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    private Integer gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.birthday
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    private Date birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.iconid
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    private Integer iconid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.location
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    private String location;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.regip
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    private String regip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.regtime
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    private Date regtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.lastip
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    private String lastip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.lasttime
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    private Date lasttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.truename
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    private String truename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.telephone
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    private String telephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.isadmin
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    private Integer isadmin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.creates
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    private Integer creates;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.focus
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    private Integer focus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.views
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    private Integer views;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.checkup
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    private Integer checkup;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.id
     *
     * @return the value of user.id
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.id
     *
     * @param id the value for user.id
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.email
     *
     * @return the value of user.email
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.email
     *
     * @param email the value for user.email
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.password
     *
     * @return the value of user.password
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.password
     *
     * @param password the value for user.password
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.nickname
     *
     * @return the value of user.nickname
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.nickname
     *
     * @param nickname the value for user.nickname
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.gender
     *
     * @return the value of user.gender
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    public Integer getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.gender
     *
     * @param gender the value for user.gender
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    public void setGender(Integer gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.birthday
     *
     * @return the value of user.birthday
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.birthday
     *
     * @param birthday the value for user.birthday
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.iconid
     *
     * @return the value of user.iconid
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    public Integer getIconid() {
        return iconid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.iconid
     *
     * @param iconid the value for user.iconid
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    public void setIconid(Integer iconid) {
        this.iconid = iconid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.location
     *
     * @return the value of user.location
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.location
     *
     * @param location the value for user.location
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    public void setLocation(String location) {
        this.location = location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.regip
     *
     * @return the value of user.regip
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    public String getRegip() {
        return regip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.regip
     *
     * @param regip the value for user.regip
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    public void setRegip(String regip) {
        this.regip = regip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.regtime
     *
     * @return the value of user.regtime
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    public Date getRegtime() {
        return regtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.regtime
     *
     * @param regtime the value for user.regtime
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    public void setRegtime(Date regtime) {
        this.regtime = regtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.lastip
     *
     * @return the value of user.lastip
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    public String getLastip() {
        return lastip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.lastip
     *
     * @param lastip the value for user.lastip
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    public void setLastip(String lastip) {
        this.lastip = lastip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.lasttime
     *
     * @return the value of user.lasttime
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    public Date getLasttime() {
        return lasttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.lasttime
     *
     * @param lasttime the value for user.lasttime
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    public void setLasttime(Date lasttime) {
        this.lasttime = lasttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.truename
     *
     * @return the value of user.truename
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    public String getTruename() {
        return truename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.truename
     *
     * @param truename the value for user.truename
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    public void setTruename(String truename) {
        this.truename = truename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.telephone
     *
     * @return the value of user.telephone
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.telephone
     *
     * @param telephone the value for user.telephone
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.isadmin
     *
     * @return the value of user.isadmin
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    public Integer getIsadmin() {
        return isadmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.isadmin
     *
     * @param isadmin the value for user.isadmin
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    public void setIsadmin(Integer isadmin) {
        this.isadmin = isadmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.creates
     *
     * @return the value of user.creates
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    public Integer getCreates() {
        return creates;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.creates
     *
     * @param creates the value for user.creates
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    public void setCreates(Integer creates) {
        this.creates = creates;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.focus
     *
     * @return the value of user.focus
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    public Integer getFocus() {
        return focus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.focus
     *
     * @param focus the value for user.focus
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    public void setFocus(Integer focus) {
        this.focus = focus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.views
     *
     * @return the value of user.views
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    public Integer getViews() {
        return views;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.views
     *
     * @param views the value for user.views
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    public void setViews(Integer views) {
        this.views = views;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.checkup
     *
     * @return the value of user.checkup
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    public Integer getCheckup() {
        return checkup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.checkup
     *
     * @param checkup the value for user.checkup
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    public void setCheckup(Integer checkup) {
        this.checkup = checkup;
    }
}