package com.lishibook.entity;

import java.util.Date;

public class UserLinkRequest {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_link_request.id
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_link_request.fromuid
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    private Integer fromuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_link_request.touid
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    private Integer touid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_link_request.time
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    private Date time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_link_request.status
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_link_request.id
     *
     * @return the value of user_link_request.id
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_link_request.id
     *
     * @param id the value for user_link_request.id
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_link_request.fromuid
     *
     * @return the value of user_link_request.fromuid
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    public Integer getFromuid() {
        return fromuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_link_request.fromuid
     *
     * @param fromuid the value for user_link_request.fromuid
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    public void setFromuid(Integer fromuid) {
        this.fromuid = fromuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_link_request.touid
     *
     * @return the value of user_link_request.touid
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    public Integer getTouid() {
        return touid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_link_request.touid
     *
     * @param touid the value for user_link_request.touid
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    public void setTouid(Integer touid) {
        this.touid = touid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_link_request.time
     *
     * @return the value of user_link_request.time
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_link_request.time
     *
     * @param time the value for user_link_request.time
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_link_request.status
     *
     * @return the value of user_link_request.status
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_link_request.status
     *
     * @param status the value for user_link_request.status
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}