package com.lishibook.entity;

import java.util.Date;

public class UserTopic {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_topic.id
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_topic.uid
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_topic.title
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_topic.content
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    private Integer content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_topic.time
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    private Date time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_topic.lastedit
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    private Date lastedit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_topic.views
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    private Integer views;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_topic.replys
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    private Integer replys;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_topic.status
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_topic.id
     *
     * @return the value of user_topic.id
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_topic.id
     *
     * @param id the value for user_topic.id
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_topic.uid
     *
     * @return the value of user_topic.uid
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_topic.uid
     *
     * @param uid the value for user_topic.uid
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_topic.title
     *
     * @return the value of user_topic.title
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_topic.title
     *
     * @param title the value for user_topic.title
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_topic.content
     *
     * @return the value of user_topic.content
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    public Integer getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_topic.content
     *
     * @param content the value for user_topic.content
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    public void setContent(Integer content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_topic.time
     *
     * @return the value of user_topic.time
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_topic.time
     *
     * @param time the value for user_topic.time
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_topic.lastedit
     *
     * @return the value of user_topic.lastedit
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    public Date getLastedit() {
        return lastedit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_topic.lastedit
     *
     * @param lastedit the value for user_topic.lastedit
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    public void setLastedit(Date lastedit) {
        this.lastedit = lastedit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_topic.views
     *
     * @return the value of user_topic.views
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    public Integer getViews() {
        return views;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_topic.views
     *
     * @param views the value for user_topic.views
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    public void setViews(Integer views) {
        this.views = views;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_topic.replys
     *
     * @return the value of user_topic.replys
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    public Integer getReplys() {
        return replys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_topic.replys
     *
     * @param replys the value for user_topic.replys
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    public void setReplys(Integer replys) {
        this.replys = replys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_topic.status
     *
     * @return the value of user_topic.status
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_topic.status
     *
     * @param status the value for user_topic.status
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}