package com.lishibook.entity;

import java.util.Date;

public class UserLink {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_link.id
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_link.fromuid
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    private Integer fromuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_link.touid
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    private Integer touid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_link.time
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    private Date time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_link.deleted
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    private Integer deleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_link.id
     *
     * @return the value of user_link.id
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_link.id
     *
     * @param id the value for user_link.id
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_link.fromuid
     *
     * @return the value of user_link.fromuid
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    public Integer getFromuid() {
        return fromuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_link.fromuid
     *
     * @param fromuid the value for user_link.fromuid
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    public void setFromuid(Integer fromuid) {
        this.fromuid = fromuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_link.touid
     *
     * @return the value of user_link.touid
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    public Integer getTouid() {
        return touid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_link.touid
     *
     * @param touid the value for user_link.touid
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    public void setTouid(Integer touid) {
        this.touid = touid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_link.time
     *
     * @return the value of user_link.time
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_link.time
     *
     * @param time the value for user_link.time
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_link.deleted
     *
     * @return the value of user_link.deleted
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    public Integer getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_link.deleted
     *
     * @param deleted the value for user_link.deleted
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    public void setDeleted(Integer deleted) {
        this.deleted = deleted;
    }
}