package com.lishibook.entity;

import java.util.Date;

public class UserFocusResource {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_focus_resource.id
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_focus_resource.userid
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_focus_resource.resourceid
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    private Integer resourceid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_focus_resource.description
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_focus_resource.time
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    private Date time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_focus_resource.deleted
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    private Integer deleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_focus_resource.id
     *
     * @return the value of user_focus_resource.id
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_focus_resource.id
     *
     * @param id the value for user_focus_resource.id
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_focus_resource.userid
     *
     * @return the value of user_focus_resource.userid
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_focus_resource.userid
     *
     * @param userid the value for user_focus_resource.userid
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_focus_resource.resourceid
     *
     * @return the value of user_focus_resource.resourceid
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    public Integer getResourceid() {
        return resourceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_focus_resource.resourceid
     *
     * @param resourceid the value for user_focus_resource.resourceid
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    public void setResourceid(Integer resourceid) {
        this.resourceid = resourceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_focus_resource.description
     *
     * @return the value of user_focus_resource.description
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_focus_resource.description
     *
     * @param description the value for user_focus_resource.description
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_focus_resource.time
     *
     * @return the value of user_focus_resource.time
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_focus_resource.time
     *
     * @param time the value for user_focus_resource.time
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_focus_resource.deleted
     *
     * @return the value of user_focus_resource.deleted
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    public Integer getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_focus_resource.deleted
     *
     * @param deleted the value for user_focus_resource.deleted
     *
     * @mbggenerated Mon Jan 20 21:49:46 CST 2014
     */
    public void setDeleted(Integer deleted) {
        this.deleted = deleted;
    }
}