package com.lishibook.entity;

import java.util.Date;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.id
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.email
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.username
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.password
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.gender
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    private Integer gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.birthday
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    private Integer birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.iconid
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    private Integer iconid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.regip
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    private String regip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.regtime
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    private Date regtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.lastip
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    private String lastip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.lasttime
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    private Date lasttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.truename
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    private String truename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.telephone
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    private String telephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.admin
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    private Integer admin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.topics
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    private Integer topics;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.collection
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    private Integer collection;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.focususers
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    private Integer focususers;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.befocused
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    private Integer befocused;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.checkup
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    private Integer checkup;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.id
     *
     * @return the value of user.id
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.id
     *
     * @param id the value for user.id
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.email
     *
     * @return the value of user.email
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.email
     *
     * @param email the value for user.email
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.username
     *
     * @return the value of user.username
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.username
     *
     * @param username the value for user.username
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.password
     *
     * @return the value of user.password
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.password
     *
     * @param password the value for user.password
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.gender
     *
     * @return the value of user.gender
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    public Integer getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.gender
     *
     * @param gender the value for user.gender
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    public void setGender(Integer gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.birthday
     *
     * @return the value of user.birthday
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    public Integer getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.birthday
     *
     * @param birthday the value for user.birthday
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    public void setBirthday(Integer birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.iconid
     *
     * @return the value of user.iconid
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    public Integer getIconid() {
        return iconid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.iconid
     *
     * @param iconid the value for user.iconid
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    public void setIconid(Integer iconid) {
        this.iconid = iconid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.regip
     *
     * @return the value of user.regip
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    public String getRegip() {
        return regip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.regip
     *
     * @param regip the value for user.regip
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    public void setRegip(String regip) {
        this.regip = regip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.regtime
     *
     * @return the value of user.regtime
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    public Date getRegtime() {
        return regtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.regtime
     *
     * @param regtime the value for user.regtime
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    public void setRegtime(Date regtime) {
        this.regtime = regtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.lastip
     *
     * @return the value of user.lastip
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    public String getLastip() {
        return lastip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.lastip
     *
     * @param lastip the value for user.lastip
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    public void setLastip(String lastip) {
        this.lastip = lastip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.lasttime
     *
     * @return the value of user.lasttime
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    public Date getLasttime() {
        return lasttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.lasttime
     *
     * @param lasttime the value for user.lasttime
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    public void setLasttime(Date lasttime) {
        this.lasttime = lasttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.truename
     *
     * @return the value of user.truename
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    public String getTruename() {
        return truename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.truename
     *
     * @param truename the value for user.truename
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    public void setTruename(String truename) {
        this.truename = truename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.telephone
     *
     * @return the value of user.telephone
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.telephone
     *
     * @param telephone the value for user.telephone
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.admin
     *
     * @return the value of user.admin
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    public Integer getAdmin() {
        return admin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.admin
     *
     * @param admin the value for user.admin
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    public void setAdmin(Integer admin) {
        this.admin = admin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.topics
     *
     * @return the value of user.topics
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    public Integer getTopics() {
        return topics;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.topics
     *
     * @param topics the value for user.topics
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    public void setTopics(Integer topics) {
        this.topics = topics;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.collection
     *
     * @return the value of user.collection
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    public Integer getCollection() {
        return collection;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.collection
     *
     * @param collection the value for user.collection
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    public void setCollection(Integer collection) {
        this.collection = collection;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.focususers
     *
     * @return the value of user.focususers
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    public Integer getFocususers() {
        return focususers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.focususers
     *
     * @param focususers the value for user.focususers
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    public void setFocususers(Integer focususers) {
        this.focususers = focususers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.befocused
     *
     * @return the value of user.befocused
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    public Integer getBefocused() {
        return befocused;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.befocused
     *
     * @param befocused the value for user.befocused
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    public void setBefocused(Integer befocused) {
        this.befocused = befocused;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.checkup
     *
     * @return the value of user.checkup
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    public Integer getCheckup() {
        return checkup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.checkup
     *
     * @param checkup the value for user.checkup
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    public void setCheckup(Integer checkup) {
        this.checkup = checkup;
    }
}